[package]
name = "boomerang_federated"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3"
bytes = "1.4"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
tinymap.workspace = true
tokio = { version = "1.27", features = ["full"] }
tokio-stream = "0.1"
tokio-util = { version = "*", features = ["codec"] }
tracing.workspace = true
thiserror.workspace = true
anyhow.workspace = true
test-log = { version = "0.2", features = ["trace"] }

[dev-dependencies]
tokio-test = "0.4"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
env_logger = "0.10"
