[package]
name = "boomerang_federated"
description = "Portable wire tag and delay primitives for Boomerang."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"
exclude.workspace = true

[features]
default = ["serde"]

## Serde derives for portable wire tags and delays
serde = []

[dependencies]
tinymap = { workspace = true }
serde = { workspace = true, features = ["derive"] }
postcard = { version = "1.1.3", default-features = false }

[dev-dependencies]
serde_json.workspace = true
