[package]
name = "boomerang_federated"
description = "Portable wire tag and delay primitives for Boomerang."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"
exclude.workspace = true

[features]
default = ["serde"]

## Serde derives for portable wire tags and delays
serde = ["dep:serde"]

[dependencies]
serde = { workspace = true, optional = true, features = ["derive"] }

[dev-dependencies]
serde_json.workspace = true
