//#include "pqueue.c"
#define NUMBER_OF_FEDERATES 1
//#include "reactor.c"
#include "reactor.h"

// Code generated by the Lingua Franca compiler for reactor HelloWorld in /home/hughesjo/Source/lingua-franca/xtext/org.icyphy.linguafranca/src/test/C/HelloWorld.lf
// =============== START reactor class HelloWorld
#line 4 "file:/home/hughesjo/Source/lingua-franca/bin/../xtext/org.icyphy.linguafranca/src/test/C/HelloWorld.lf"
#line 6 "file:/home/hughesjo/Source/lingua-franca/bin/../xtext/org.icyphy.linguafranca/src/test/C/HelloWorld.lf"
#line 5 "file:/home/hughesjo/Source/lingua-franca/bin/../xtext/org.icyphy.linguafranca/src/test/C/HelloWorld.lf"
typedef struct {
    int i;
    int* __in;
    bool* __in_is_present;
    int __c;
    bool __c_is_present;
} helloworld_self_t;
void helloworld_rfunc_0(void* instance_args) {
    helloworld_self_t* self = (helloworld_self_t*)instance_args;
    int* c = &(self->__c);
    bool c_is_present = self->__c_is_present;
    #line 8 "file:/home/hughesjo/Source/lingua-franca/bin/../xtext/org.icyphy.linguafranca/src/test/C/HelloWorld.lf"
    printf("Hello World.\n");
    (self->i)++;
    set(c, self->i);
}
void helloworld_rfunc_1(void* instance_args) {
    helloworld_self_t* self = (helloworld_self_t*)instance_args;
    bool in_is_present = *(self->__in_is_present);
    int in;
    if(in_is_present) {
        in = *(self->__in);
    }
    #line 14 "file:/home/hughesjo/Source/lingua-franca/bin/../xtext/org.icyphy.linguafranca/src/test/C/HelloWorld.lf"
    printf("i = %i.\n", self->i);
}
// =============== END reactor class HelloWorld

// Code generated by the Lingua Franca compiler for reactor HelloWorldTest in /home/hughesjo/Source/lingua-franca/xtext/org.icyphy.linguafranca/src/test/C/HelloWorld.lf
// =============== START reactor class HelloWorldTest
// =============== END reactor class HelloWorldTest

// ************* Instance HelloWorldTest of class HelloWorldTest


// ************* Instance HelloWorldTest.a of class HelloWorld
// --- "self" struct for instance HelloWorldTest.a
helloworld_self_t helloworldtest_a_self;
bool* helloworldtest_a_reaction_0_outputs_are_present[] = {&helloworldtest_a_self.__c_is_present};
int helloworldtest_a_reaction_0_triggered_sizes[] = {0};
trigger_t** helloworldtest_a_reaction_0_triggers[] = {NULL};
reaction_t helloworldtest_a_reaction_0 = {&helloworld_rfunc_0, &helloworldtest_a_self, 0, 0, 0, 1, helloworldtest_a_reaction_0_outputs_are_present, &helloworldtest_a_reaction_0_triggered_sizes[0], &helloworldtest_a_reaction_0_triggers[0], false, 0LL, NULL};
reaction_t helloworldtest_a_reaction_1 = {&helloworld_rfunc_1, &helloworldtest_a_self, 0, 0, 0, 0, NULL, NULL, NULL, false, 0LL, NULL};
// --- Reaction and trigger objects for reaction to trigger foo of instance HelloWorldTest.a
reaction_t* helloworldtest_a_foo_trigger_reactions[1] = {&helloworldtest_a_reaction_0};
trigger_t helloworldtest_a_foo_trigger = {
    helloworldtest_a_foo_trigger_reactions, 1, 0LL, 0LL, NULL, false, NEVER, NONE
};
// --- Reaction and trigger objects for reaction to trigger in of instance HelloWorldTest.a
reaction_t* helloworldtest_a_in_trigger_reactions[1] = {&helloworldtest_a_reaction_1};
trigger_t helloworldtest_a_in_trigger = {
    helloworldtest_a_in_trigger_reactions, 1, 0LL, 0LL, NULL, false, NEVER, NONE
};
// ************* Instance HelloWorldTest.b of class HelloWorld
// --- "self" struct for instance HelloWorldTest.b
helloworld_self_t helloworldtest_b_self;
bool* helloworldtest_b_reaction_0_outputs_are_present[] = {&helloworldtest_b_self.__c_is_present};
int helloworldtest_b_reaction_0_triggered_sizes[] = {0};
trigger_t** helloworldtest_b_reaction_0_triggers[] = {NULL};
reaction_t helloworldtest_b_reaction_0 = {&helloworld_rfunc_0, &helloworldtest_b_self, 0, 0, 0, 1, helloworldtest_b_reaction_0_outputs_are_present, &helloworldtest_b_reaction_0_triggered_sizes[0], &helloworldtest_b_reaction_0_triggers[0], false, 0LL, NULL};
reaction_t helloworldtest_b_reaction_1 = {&helloworld_rfunc_1, &helloworldtest_b_self, 0, 0, 0, 0, NULL, NULL, NULL, false, 0LL, NULL};
// --- Reaction and trigger objects for reaction to trigger in of instance HelloWorldTest.b
reaction_t* helloworldtest_b_in_trigger_reactions[1] = {&helloworldtest_b_reaction_1};
trigger_t helloworldtest_b_in_trigger = {
    helloworldtest_b_in_trigger_reactions, 1, 0LL, 0LL, NULL, false, NEVER, NONE
};
// --- Reaction and trigger objects for reaction to trigger foo of instance HelloWorldTest.b
reaction_t* helloworldtest_b_foo_trigger_reactions[1] = {&helloworldtest_b_reaction_0};
trigger_t helloworldtest_b_foo_trigger = {
    helloworldtest_b_foo_trigger_reactions, 1, 0LL, 0LL, NULL, false, NEVER, NONE
};
void __set_default_command_line_options() {
}
void __initialize_trigger_objects() {
    //***** Start initializing HelloWorldTest
    //***** Start initializing HelloWorldTest.a
    static int helloworldtest_a_initial_i = 0;
    helloworldtest_a_self.i = helloworldtest_a_initial_i;
    helloworldtest_a_foo_trigger.offset = MSEC(100);
    helloworldtest_a_foo_trigger.period = MSEC(1000);
    //***** End initializing HelloWorldTest.a
    //***** Start initializing HelloWorldTest.b
    static int helloworldtest_b_initial_i = 0;
    helloworldtest_b_self.i = helloworldtest_b_initial_i;
    helloworldtest_b_foo_trigger.offset = MSEC(100);
    helloworldtest_b_foo_trigger.period = MSEC(1000);
    //***** End initializing HelloWorldTest.b
    //***** End initializing HelloWorldTest
    // doDeferredInitialize
    helloworldtest_a_self.__in_is_present = &False;
    helloworldtest_b_self.__in_is_present = &False;
    // Connect inputs and outputs.
    // Connect inputs and outputs.
    // Connect inputs and outputs.
    helloworldtest_a_reaction_0.index = 0;
    helloworldtest_a_reaction_0.chain_id = 1;
    helloworldtest_a_reaction_0.index = 9223372036854710272LL;
    helloworldtest_a_reaction_1.index = 1;
    helloworldtest_a_reaction_1.chain_id = 1;
    helloworldtest_a_reaction_1.index = 9223372036854710273LL;
    helloworldtest_b_reaction_0.index = 0;
    helloworldtest_b_reaction_0.chain_id = 4;
    helloworldtest_b_reaction_0.index = 9223372036854710272LL;
    helloworldtest_b_reaction_1.index = 1;
    helloworldtest_b_reaction_1.chain_id = 2;
    helloworldtest_b_reaction_1.index = 9223372036854710273LL;
}
void __start_timers() {
    __schedule(&helloworldtest_a_foo_trigger, 0LL, NULL);
    __schedule(&helloworldtest_b_foo_trigger, 0LL, NULL);
}
void __start_time_step() {
    helloworldtest_a_self.__c_is_present = false;
    helloworldtest_b_self.__c_is_present = false;
}
bool __wrapup() {
    return false;
}
