[package]
name = 'boomerang_derive'
version = '0.1.0'
authors = ['John Hughes <jondo2010@gmail.com>']
edition = '2018'
license = 'MIT OR Apache-2.0'
description = 'Macros implementation'

[dependencies]
darling = '0.10.2'
derive_more = "0.99.5"
parse_duration = "2.1.0"
petgraph = "0.5.0"
proc-macro2 = '1.0'
quote = '1.0'
syn = { version = '1.0', features = ['visit'] }

[lib]
name = 'boomerang_derive'
proc-macro = true
