[package]
name = 'boomerang_derive'
version = '0.1.0'
authors = ['John Hughes <jondo2010@gmail.com>']
edition = '2018'
license = 'MIT OR Apache-2.0'
description = 'Macros implementation'

[dependencies]
proc-macro2 = '1.0'
quote = '1.0'
syn = { version = '1.0', features = ['visit'] }

[lib]
name = 'boomerang_derive'
proc-macro = true
