[package]
name = "sensor-host"
version = "0.1.0"
edition = "2021"

[features]
simulated = []
runtime-failure = []
natural-quiescence = []

[dependencies]
boomerang = { path = "../../../../../boomerang" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(boomerang_facet, values("descriptor", "payload"))'] }
