[package]
name = "cargo-boomerang"
description = "Static deployment tooling for Boomerang"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
anstream = "1.0"
anyhow.workspace = true
blake3.workspace = true
boomerang_builder = { workspace = true, features = ["descriptor-fingerprint", "host-interchange"] }
boomerang_runtime.workspace = true
cargo_metadata.workspace = true
fs2.workspace = true
humantime.workspace = true
clap = { version = "4.2", features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_path_to_error.workspace = true
serde_json.workspace = true
tempfile.workspace = true
target-lexicon = "0.13"
tinymap.workspace = true
toml.workspace = true
tracing-subscriber = { version = "=0.3.23", default-features = false, features = [
    "env-filter",
    "fmt",
] }

[[bin]]
name = "cargo-boomerang"
path = "src/main.rs"
