[package]
name = "cargo-boomerang"
description = "Static deployment tooling for Boomerang"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
blake3.workspace = true
cargo_metadata.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_path_to_error.workspace = true
thiserror.workspace = true
toml.workspace = true

[dev-dependencies]
tempfile.workspace = true

[[bin]]
name = "cargo-boomerang"
path = "src/main.rs"
