[package]
name = "vehicle-control"
version = "0.1.0"
edition = "2021"

[features]
default = ["boomerang/hosted"]
__boomerang_descriptor = ["boomerang/__boomerang_descriptor"]
__boomerang_payload = ["boomerang/__boomerang_payload"]
controller-selected = []
sensor-selected = []

[dependencies]
boomerang = { path = "../../../../../boomerang", default-features = false }
