[package]
name = 'boomerang_util'
description = 'Rust implementation of "Reactors" Deterministic Actor Model'
version = '0.2.0'
authors = ['John Hughes <jondo2010@gmail.com>']
edition = '2021'
license = 'MIT OR Apache-2.0'
readme = 'README.md'
keywords = ['actor', 'reactor']
repository = 'https://gitlab.com/jondo2010/boomerang'
documentation = 'https://docs.rs/boomerang'
categories = []
exclude = ['.gitignore', '.cargo/config', '.gitlab-ci.yml']

[dependencies]
anyhow = "1.0"
boomerang = { path = "../boomerang" }
clap = { version = "4.1", features = ["derive"] }
tracing = "0.1"