[package]
name = 'boomerang_util'
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[features]
default = ["keyboard", "runner"]
# Support for keyboard input
keyboard = ["termion"]
# Support for built-in CLI/runner methods
runner = ["clap", "anyhow"]
federated = ["dep:tokio"]

[dependencies]
anyhow = { version = "1.0", optional = true }
clap = { version = "4.2", features = ["derive"], optional = true }
tokio = { workspace = true, optional = true, features = ["rt"] }
tracing = "0.1"

boomerang.workspace = true

[target.'cfg(not(windows))'.dependencies]
termion = {version = "2.0", optional = true}

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["fmt", "json", "env-filter"] }