[package]
name = "boomerang_util"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[features]
default = ["keyboard"]
# Support for keyboard input
keyboard = ["termion"]

[dependencies]
#tokio = { workspace = true, optional = true, features = ["rt"] }
tracing = "0.1"

boomerang = { path = "../" }

[target.'cfg(not(windows))'.dependencies]
termion = { version = "2.0", optional = true }

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["fmt", "json", "env-filter"] }