[package]
name = 'boomerang_util'
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[features]
default = [
    "keyboard",
    "runner",
    #"replay"
    "serde",
]

## Support for keyboard input
keyboard = ["dep:termion"]

## Support for built-in CLI/runner methods
runner = ["dep:clap", "dep:anyhow"]

## Support for serde serialization
serde = ["dep:serde", "dep:erased-serde", "termion/serde", "boomerang/serde"]

# Support for recording and replaying
#replay = ["serde", "dep:bincode"]

[dependencies]
anyhow = { version = "1.0", optional = true }
bincode = { version = "1.3", optional = true }
clap = { version = "4.2", features = ["derive"], optional = true }
document-features = { workspace = true }
erased-serde = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
tracing = "0.1"

serde_json = { version = "1.0" }

boomerang.workspace = true
boomerang_tinymap.workspace = true

[target.'cfg(not(windows))'.dependencies]
termion = { version = "2.0", optional = true }

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = [
    "fmt",
    "json",
    "env-filter",
] }
