[package]
name = "boomerang_central_rti"
description = "Compiled central RTI execution for Boomerang federations."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"
exclude.workspace = true

[dependencies]
boomerang_federated.workspace = true
boomerang_runtime.workspace = true
tinymap.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
bytes = "1"
futures-util = { version = "0.3", features = ["sink"] }
tokio = { version = "1", features = ["rt", "net", "sync", "time", "macros", "io-util"] }
tokio-util = { version = "0.7", features = ["codec", "rt"] }

[dev-dependencies]
boomerang_federated = { workspace = true, features = ["conformance"] }
tokio = { version = "1", features = ["test-util"] }
