use std::{collections::BTreeMap, fmt::Write as _};

use anyhow::{anyhow, bail, Result};
use boomerang_builder::{
    compiler::{OwnedCompiledDeployment, OwnedEnclaveImage, RequiredBinding},
    ComponentDescriptor, DescriptorLifecycle, DescriptorRelationshipKind,
    DescriptorRelationshipTarget, ReactionSlot, ReactionSlotId, ReactorSlotId,
};
use boomerang_runtime::{
    image::{
        ActionTiming, BankInfoImage, BindingKind, EnclaveImage, IdentityRange, LevelReactionImage,
        LifecycleReactionImage, RouteDirection, StorageBounds, TimerStartupImage, TimingDomain,
    },
    TransitionKind,
};
use tinymap::TableRange;

use crate::DriverOutput;

/// Renders one complete static launcher source file from validated compiler output.
pub(super) fn render_launcher(
    driver: &DriverOutput,
    compiled: &OwnedCompiledDeployment,
    federate_index: usize,
    aliases: &BTreeMap<String, String>,
) -> Result<String> {
    let federate = compiled
        .federates()
        .get(federate_index)
        .ok_or_else(|| anyhow!("compiled Federate index {federate_index} is out of range"))?;
    let mut source = String::from(
        "// @generated by cargo-boomerang; do not edit.\n\
         use boomerang_runtime::{execute_owned_federate, Config, EnclaveBindings, \
         FederateBindings, ReactorData};\n\
         use boomerang_runtime::image::*;\n\
         use tinymap::{TableRange, TinyMapView};\n\n\
         fn generated_state<'a, T: ReactorData>(\n\
             state: &'a mut dyn ReactorData,\n\
             _initializer: fn() -> T,\n\
         ) -> &'a mut T {\n\
             state.downcast_mut::<T>()\n\
                 .expect(\"generated state initializer and reaction must agree\")\n\
         }\n\n",
    );

    render_compatibility_checks(&mut source, driver, aliases)?;
    for (index, enclave) in federate.enclaves().iter().enumerate() {
        render_enclave(&mut source, index, enclave)?;
    }
    render_deployment(&mut source, federate)?;
    render_bindings(&mut source, driver, federate.enclaves(), aliases)?;
    source.push_str(
        "fn main() -> Result<(), Box<dyn std::error::Error>> {\n\
             let bindings = generated_bindings();\n\
             let _execution = execute_owned_federate(\n\
                 &DEPLOYMENT, FederateIndex::new(0), bindings, Config {\n\
                     fast_forward: false,\n\
                     timeout: None,\n\
                     keep_alive: false,\n\
                     physical_event_q_size: 1024,\n\
                 },\n\
             )?;\n\
             Ok(())\n\
         }\n",
    );
    Ok(source)
}

/// Emits independent const checks for every selected descriptor/payload pair.
fn render_compatibility_checks(
    source: &mut String,
    driver: &DriverOutput,
    aliases: &BTreeMap<String, String>,
) -> Result<()> {
    for binding in driver.bindings() {
        let implementation = binding.implementation().as_str();
        let Some(alias) = aliases.get(implementation) else {
            continue;
        };
        let descriptor = binding.descriptor();
        let bytes = descriptor
            .descriptor_fingerprint_input()
            .fingerprint()
            .to_bytes();
        writeln!(
            source,
            "const _: () = boomerang_runtime::binding::assert_descriptor_fingerprint(\n    \
             boomerang_runtime::binding::DescriptorFingerprint::new({bytes:?}),\n    \
             {alias}::__boomerang::BINDING_MANIFEST.descriptor_fingerprint(),\n);"
        )?;
        writeln!(
            source,
            "const _: () = assert!({abi} == \
             {alias}::__boomerang::BINDING_MANIFEST.macro_abi(), \
             \"macro ABI mismatch\");\n",
            abi = descriptor.macro_abi(),
        )?;
    }
    Ok(())
}

/// Emits every immutable scheduler table for one compiled Enclave.
fn render_enclave(source: &mut String, index: usize, owned: &OwnedEnclaveImage) -> Result<()> {
    let image = owned.image();
    let prefix = format!("E{index}");
    render_reactors(source, &prefix, &image)?;
    render_actions(source, &prefix, &image)?;
    render_ports(source, &prefix, &image)?;
    render_reactions(source, &prefix, &image)?;
    render_modes(source, &prefix, &image)?;
    render_scopes(source, &prefix, &image)?;
    render_level_reactions(
        source,
        &format!("{prefix}_REACTION_TRIGGERS"),
        image.reaction_triggers,
    )?;
    render_indices(
        source,
        &format!("{prefix}_REACTION_USE_PORTS"),
        "PortIndex",
        image.reaction_use_ports.iter().map(|value| value.as_u32()),
    )?;
    render_indices(
        source,
        &format!("{prefix}_REACTION_EFFECT_PORTS"),
        "PortIndex",
        image
            .reaction_effect_ports
            .iter()
            .map(|value| value.as_u32()),
    )?;
    render_indices(
        source,
        &format!("{prefix}_REACTION_ACTIONS"),
        "ActionIndex",
        image.reaction_actions.iter().map(|value| value.as_u32()),
    )?;
    render_indices(
        source,
        &format!("{prefix}_REACTION_MODES"),
        "ModeIndex",
        image.reaction_modes.iter().map(|value| value.as_u32()),
    )?;
    render_indices(
        source,
        &format!("{prefix}_SCOPE_DESCENDANTS"),
        "ScopeIndex",
        image.scope_descendants.iter().map(|value| value.as_u32()),
    )?;
    render_indices(
        source,
        &format!("{prefix}_SCOPE_LOGICAL_ACTIONS"),
        "ActionIndex",
        image
            .scope_logical_actions
            .iter()
            .map(|value| value.as_u32()),
    )?;
    render_timer_startups(
        source,
        &format!("{prefix}_SCOPE_TIMER_STARTUPS"),
        image.scope_timer_startups,
    )?;
    render_level_reactions(
        source,
        &format!("{prefix}_SCOPE_RESET_REACTIONS"),
        image.scope_reset_reactions,
    )?;
    render_lifecycle_reactions(
        source,
        &format!("{prefix}_SCOPE_STARTUP_REACTIONS"),
        image.scope_startup_reactions,
    )?;
    render_lifecycle_reactions(
        source,
        &format!("{prefix}_SCOPE_SHUTDOWN_REACTIONS"),
        image.scope_shutdown_reactions,
    )?;
    render_timer_startups(
        source,
        &format!("{prefix}_STARTUP_ACTIONS"),
        image.startup_actions,
    )?;
    render_timer_startups(
        source,
        &format!("{prefix}_TIMER_STARTUP_ACTIONS"),
        image.timer_startup_actions,
    )?;
    render_lifecycle_reactions(
        source,
        &format!("{prefix}_SHUTDOWN_REACTIONS"),
        image.shutdown_reactions,
    )?;
    render_indices(
        source,
        &format!("{prefix}_SHUTDOWN_ACTIONS"),
        "ActionIndex",
        image.shutdown_actions.iter().map(|value| value.as_u32()),
    )?;
    render_routes(source, &prefix, &image)?;
    render_required_bindings(source, &prefix, &image)?;
    let bounds = image.storage_bounds;
    writeln!(
        source,
        "static {prefix}_IDENTITIES: &str = {:?};",
        image.identity_data
    )?;
    writeln!(
        source,
        "static {prefix}_IMAGE: EnclaveImage<'static> = EnclaveImage {{"
    )?;
    writeln!(source, "    identity_data: {prefix}_IDENTITIES,")?;
    writeln!(
        source,
        "    enclave_id: {},",
        identity_range(image.enclave_id)
    )?;
    for (field, table) in [
        ("reactors", "REACTORS"),
        ("actions", "ACTIONS"),
        ("ports", "PORTS"),
        ("reactions", "REACTIONS"),
        ("modes", "MODES"),
        ("scopes", "SCOPES"),
    ] {
        writeln!(source, "    {field}: TinyMapView::new(&{prefix}_{table}),")?;
    }
    for (field, table) in [
        ("reaction_triggers", "REACTION_TRIGGERS"),
        ("reaction_use_ports", "REACTION_USE_PORTS"),
        ("reaction_effect_ports", "REACTION_EFFECT_PORTS"),
        ("reaction_actions", "REACTION_ACTIONS"),
        ("reaction_modes", "REACTION_MODES"),
        ("scope_descendants", "SCOPE_DESCENDANTS"),
        ("scope_logical_actions", "SCOPE_LOGICAL_ACTIONS"),
        ("scope_timer_startups", "SCOPE_TIMER_STARTUPS"),
        ("scope_reset_reactions", "SCOPE_RESET_REACTIONS"),
        ("scope_startup_reactions", "SCOPE_STARTUP_REACTIONS"),
        ("scope_shutdown_reactions", "SCOPE_SHUTDOWN_REACTIONS"),
        ("startup_actions", "STARTUP_ACTIONS"),
        ("timer_startup_actions", "TIMER_STARTUP_ACTIONS"),
        ("shutdown_reactions", "SHUTDOWN_REACTIONS"),
        ("shutdown_actions", "SHUTDOWN_ACTIONS"),
    ] {
        writeln!(source, "    {field}: &{prefix}_{table},")?;
    }
    writeln!(source, "    routes: TinyMapView::new(&{prefix}_ROUTES),")?;
    writeln!(
        source,
        "    required_bindings: TinyMapView::new(&{prefix}_REQUIRED_BINDINGS),"
    )?;
    writeln!(source, "    storage_bounds: {},", storage_bounds(bounds))?;
    source.push_str("};\n\n");
    Ok(())
}

/// Emits the deployment root tables around the selected Federate's Enclave images.
fn render_deployment(
    source: &mut String,
    federate: &boomerang_builder::compiler::OwnedFederateImage,
) -> Result<()> {
    let id = federate.id().as_str();
    let target = federate.target().as_str();
    let runtime = federate.runtime().as_str();
    let identities = format!("{id}{target}{runtime}");
    let id_range = IdentityRange::new(0, u32::try_from(id.len())?);
    let target_range = IdentityRange::new(id_range.len(), u32::try_from(target.len())?);
    let runtime_range = IdentityRange::new(
        id_range.len() + target_range.len(),
        u32::try_from(runtime.len())?,
    );
    writeln!(
        source,
        "static DEPLOYMENT_IDENTITIES: &str = {identities:?};"
    )?;
    writeln!(source, "static FEDERATES: [FederateImage; 1] = [FederateImage::new({}, {}, {}, TableRange::new(0, {}))];", identity_range(id_range), identity_range(target_range), identity_range(runtime_range), federate.enclaves().len())?;
    write!(
        source,
        "static ENCLAVES: [EnclaveImage<'static>; {}] = [",
        federate.enclaves().len()
    )?;
    for index in 0..federate.enclaves().len() {
        write!(source, "E{index}_IMAGE,")?;
    }
    source.push_str("];\n");
    source.push_str("static FEDERATION_MEMBERS: [FederateIndex; 1] = [FederateIndex::new(0)];\n");
    source.push_str("static DEPLOYMENT: CompiledDeploymentImage<'static> = CompiledDeploymentImage {\n    identity_data: DEPLOYMENT_IDENTITIES,\n    federation: GlobalFederationImage::new(&FEDERATION_MEMBERS, &[]),\n    federates: TinyMapView::new(&FEDERATES),\n    enclaves: TinyMapView::new(&ENCLAVES),\n    coordination: CoordinationProjection::Local,\n};\n\n");
    Ok(())
}

/// Emits direct typed binding construction for every Enclave.
fn render_bindings(
    source: &mut String,
    driver: &DriverOutput,
    enclaves: &[OwnedEnclaveImage],
    aliases: &BTreeMap<String, String>,
) -> Result<()> {
    source.push_str(
        "fn generated_bindings() -> FederateBindings<'static> {\n    FederateBindings::new()\n",
    );
    for (enclave_index, enclave) in enclaves.iter().enumerate() {
        writeln!(
            source,
            "        .bind_enclave(EnclaveIndex::new({enclave_index}), EnclaveBindings::new()"
        )?;
        for (slot, binding) in enclave.required_bindings().iter().enumerate() {
            render_binding(source, driver, aliases, slot, binding)?;
        }
        source.push_str("        )\n");
    }
    render_route_bindings(source, enclaves, aliases)?;
    source.push_str("}\n\n");
    Ok(())
}

/// Emits one typed route binding for each paired local scheduler boundary.
fn render_route_bindings(
    source: &mut String,
    enclaves: &[OwnedEnclaveImage],
    aliases: &BTreeMap<String, String>,
) -> Result<()> {
    let mut routes = BTreeMap::<String, (Option<String>, Option<String>)>::new();
    for enclave in enclaves {
        let image = enclave.image();
        for route in image.routes.values().copied() {
            let boundary = route
                .boundary()
                .get(image.identity_data)
                .expect("compiled route identities are validated")
                .to_owned();
            let port = image.ports[route.local_port()];
            let binding = enclave
                .required_bindings()
                .iter()
                .nth(port.binding().as_u32() as usize)
                .expect("compiled port binding index is validated");
            let RequiredBinding::Port { implementation, .. } = binding else {
                bail!("route '{boundary}' local port does not have a port binding");
            };
            let alias = aliases.get(implementation.as_str()).ok_or_else(|| {
                anyhow!("missing generated alias for implementation '{implementation}'")
            })?;
            let payload = format!("{alias}::__boomerang::{}", binding.symbol());
            let pair = routes.entry(boundary.clone()).or_default();
            let slot = match route.direction() {
                RouteDirection::Outbound => &mut pair.0,
                RouteDirection::Inbound => &mut pair.1,
            };
            if slot.replace(payload).is_some() {
                bail!(
                    "route '{boundary}' has duplicate {:?} endpoints",
                    route.direction()
                );
            }
        }
    }
    for (boundary, (source_payload, destination_payload)) in routes {
        let source_payload =
            source_payload.ok_or_else(|| anyhow!("route '{boundary}' has no outbound endpoint"))?;
        let destination_payload = destination_payload
            .ok_or_else(|| anyhow!("route '{boundary}' has no inbound endpoint"))?;
        writeln!(
            source,
            "        .bind_route(BoundaryId::new({boundary:?}), {source_payload}, {destination_payload})"
        )?;
    }
    Ok(())
}

/// Emits one state, reaction, port, or action binding chain entry.
fn render_binding(
    source: &mut String,
    driver: &DriverOutput,
    aliases: &BTreeMap<String, String>,
    slot: usize,
    binding: &RequiredBinding,
) -> Result<()> {
    let (implementation, symbol) = match binding {
        RequiredBinding::State { implementation, .. }
        | RequiredBinding::Reaction { implementation, .. }
        | RequiredBinding::Port { implementation, .. }
        | RequiredBinding::Action { implementation, .. } => {
            (implementation.as_str(), binding.symbol())
        }
    };
    let alias = aliases
        .get(implementation)
        .ok_or_else(|| anyhow!("missing generated alias for implementation '{implementation}'"))?;
    match binding {
        RequiredBinding::State { .. } => writeln!(source, "            .bind_state(BindingSlotIndex::new({slot}), {alias}::__boomerang::{symbol})")?,
        RequiredBinding::Port { .. } => writeln!(source, "            .bind_port(BindingSlotIndex::new({slot}), {alias}::__boomerang::{symbol})")?,
        RequiredBinding::Action { .. } => writeln!(source, "            .bind_action(BindingSlotIndex::new({slot}), {alias}::__boomerang::{symbol})")?,
        RequiredBinding::Reaction { reaction, .. } => {
            let descriptor = driver
                .bindings()
                .iter()
                .find(|binding| binding.implementation().as_str() == implementation)
                .expect("required implementation has descriptor output")
                .descriptor();
            let state = reaction_reactor(descriptor.reaction_slots(), reaction)?;
            let state_symbol = boomerang_builder::compiler::direct_binding_symbol(
                BindingKind::StateInitializer,
                state.path(),
            );
            render_reaction_binding(
                source, descriptor, reaction, slot, alias, &state_symbol, &symbol,
            )?;
        }
    }
    Ok(())
}

/// Resolves a reaction slot to the exact descriptor reactor that owns it.
fn reaction_reactor<'a>(
    slots: &'a [ReactionSlot],
    reaction: &ReactionSlotId,
) -> Result<&'a ReactorSlotId> {
    slots
        .iter()
        .find(|slot| slot.id == *reaction)
        .map(|slot| &slot.reactor)
        .ok_or_else(|| anyhow!("reaction '{reaction}' has no descriptor reactor"))
}

/// Emits the erased-to-typed adapter for one generated payload reaction function.
fn render_reaction_binding(
    source: &mut String,
    descriptor: &ComponentDescriptor,
    reaction: &ReactionSlotId,
    slot: usize,
    alias: &str,
    state_symbol: &str,
    reaction_symbol: &str,
) -> Result<()> {
    let relations = descriptor
        .relationships()
        .iter()
        .filter(|relation| relation.reaction == *reaction)
        .collect::<Vec<_>>();
    let mut immutable_ports = Vec::new();
    let mut mutable_ports = Vec::new();
    let mut actions = Vec::new();
    let mut tuple = Vec::new();
    let has_mode_effect = relations.iter().any(|relation| {
        relation.kind == DescriptorRelationshipKind::Effect
            && matches!(&relation.target, DescriptorRelationshipTarget::Mode(_))
            && relation.mode_transition.is_some()
    });
    for kind in [
        DescriptorRelationshipKind::Trigger,
        DescriptorRelationshipKind::Use,
        DescriptorRelationshipKind::Effect,
    ] {
        let mut category = relations
            .iter()
            .copied()
            .filter(|relation| relation.kind == kind)
            .collect::<Vec<_>>();
        category.sort_by_key(|relation| relation.declaration_position);
        for relation in category {
            let name = match (&relation.target, kind) {
                (
                    DescriptorRelationshipTarget::Port(_),
                    DescriptorRelationshipKind::Trigger | DescriptorRelationshipKind::Use,
                ) => next_name("port", &mut immutable_ports),
                (DescriptorRelationshipTarget::Port(_), DescriptorRelationshipKind::Effect) => {
                    next_name("port_mut", &mut mutable_ports)
                }
                (DescriptorRelationshipTarget::Action(_), _) => next_name("action", &mut actions),
                (
                    DescriptorRelationshipTarget::Lifecycle(
                        DescriptorLifecycle::Startup | DescriptorLifecycle::Shutdown,
                    ),
                    DescriptorRelationshipKind::Trigger,
                ) => next_name("action", &mut actions),
                (
                    DescriptorRelationshipTarget::Lifecycle(DescriptorLifecycle::Reset),
                    DescriptorRelationshipKind::Trigger,
                ) => continue,
                (DescriptorRelationshipTarget::Mode(_), DescriptorRelationshipKind::Effect)
                    if relation.mode_transition.is_some() =>
                {
                    String::from("mode_effect.expect(\"compiled mode effect is required\")")
                }
                (_, DescriptorRelationshipKind::Mode | DescriptorRelationshipKind::Scope) => {
                    continue
                }
                (target, _) => bail!("unsupported generated reaction relationship {target:?}"),
            };
            tuple.push(name);
        }
    }
    let mode_effect = if has_mode_effect {
        "mode_effect"
    } else {
        "_mode_effect"
    };
    writeln!(source, "            .bind_reaction(BindingSlotIndex::new({slot}), |ctx, state, refs, {mode_effect}| {{")?;
    writeln!(
        source,
        "                let state = generated_state(state, {alias}::__boomerang::{state_symbol});"
    )?;
    render_partition(source, "refs.ports.partition()?", &immutable_ports)?;
    render_partition(source, "refs.ports_mut.partition_mut()?", &mutable_ports)?;
    render_partition(source, "refs.actions.partition_mut()?", &actions)?;
    write!(
        source,
        "                {alias}::__boomerang::{reaction_symbol}(ctx, state, ("
    )?;
    for value in tuple {
        write!(source, "{value},")?;
    }
    source.push_str("));\n                Ok(())\n            })\n");
    Ok(())
}

/// Allocates the next generated local name within one reference partition.
fn next_name(prefix: &str, values: &mut Vec<String>) -> String {
    let name = format!("{prefix}_{}", values.len());
    values.push(name.clone());
    name
}

/// Emits a tuple destructure whose inferred element types drive runtime reference extraction.
fn render_partition(source: &mut String, expression: &str, values: &[String]) -> Result<()> {
    if values.is_empty() {
        return Ok(());
    }
    write!(source, "                let (")?;
    for value in values {
        write!(source, "{value},")?;
    }
    writeln!(source, ") = {expression};")?;
    Ok(())
}

fn render_reactors(source: &mut String, prefix: &str, image: &EnclaveImage<'_>) -> Result<()> {
    writeln!(
        source,
        "static {prefix}_REACTORS: [ReactorImage; {}] = [",
        image.reactors.len()
    )?;
    for value in image.reactors.values() {
        writeln!(source, "    ReactorImage::new(BindingSlotIndex::new({}), StateSlotIndex::new({}), ScopeIndex::new({}), {}, {}, {}),", value.state_binding().as_u32(), value.state_slot().as_u32(), value.root_scope().as_u32(), table_range(value.modes()), optional_index("ModeIndex", value.initial_mode().map(|value| value.as_u32())), optional_bank(value.bank()))?;
    }
    source.push_str("];\n");
    Ok(())
}

fn render_actions(source: &mut String, prefix: &str, image: &EnclaveImage<'_>) -> Result<()> {
    writeln!(
        source,
        "static {prefix}_ACTIONS: [ActionImage; {}] = [",
        image.actions.len()
    )?;
    for value in image.actions.values() {
        writeln!(
            source,
            "    ActionImage::new(ScopeIndex::new({}), ActionSlotIndex::new({}), {}, {}, {}),",
            value.scope().as_u32(),
            value.storage_slot().as_u32(),
            action_timing(value.timing()),
            table_range(value.triggers()),
            optional_index(
                "BindingSlotIndex",
                value.binding().map(|value| value.as_u32())
            )
        )?;
    }
    source.push_str("];\n");
    Ok(())
}

fn render_ports(source: &mut String, prefix: &str, image: &EnclaveImage<'_>) -> Result<()> {
    writeln!(
        source,
        "static {prefix}_PORTS: [PortImage; {}] = [",
        image.ports.len()
    )?;
    for value in image.ports.values() {
        writeln!(
            source,
            "    PortImage::new(ScopeIndex::new({}), {}, BindingSlotIndex::new({})),",
            value.scope().as_u32(),
            table_range(value.triggers()),
            value.binding().as_u32()
        )?;
    }
    source.push_str("];\n");
    Ok(())
}

fn render_reactions(source: &mut String, prefix: &str, image: &EnclaveImage<'_>) -> Result<()> {
    writeln!(
        source,
        "static {prefix}_REACTIONS: [ReactionImage; {}] = [",
        image.reactions.len()
    )?;
    for value in image.reactions.values() {
        write!(source, "    ReactionImage::new(ReactorIndex::new({}), ScopeIndex::new({}), {}, BindingSlotIndex::new({}), {}, {}, {}, {})", value.reactor().as_u32(), value.scope().as_u32(), value.dependency_level(), value.binding().as_u32(), table_range(value.use_ports()), table_range(value.effect_ports()), table_range(value.actions()), table_range(value.enabled_modes()))?;
        if let Some(effect) = value.mode_effect() {
            write!(source, ".with_mode_effect(boomerang_runtime::CompiledModeEffectRef {{ target: ModeIndex::new({}), transition: boomerang_runtime::TransitionKind::{} }})", effect.target.as_u32(), transition(effect.transition))?;
        }
        source.push_str(",\n");
    }
    source.push_str("];\n");
    Ok(())
}

fn render_modes(source: &mut String, prefix: &str, image: &EnclaveImage<'_>) -> Result<()> {
    writeln!(
        source,
        "static {prefix}_MODES: [ModeImage; {}] = [",
        image.modes.len()
    )?;
    for value in image.modes.values() {
        writeln!(
            source,
            "    ModeImage::new(ReactorIndex::new({}), ScopeIndex::new({})),",
            value.reactor().as_u32(),
            value.scope().as_u32()
        )?;
    }
    source.push_str("];\n");
    Ok(())
}

fn render_scopes(source: &mut String, prefix: &str, image: &EnclaveImage<'_>) -> Result<()> {
    writeln!(
        source,
        "static {prefix}_SCOPES: [ScopeImage; {}] = [",
        image.scopes.len()
    )?;
    for value in image.scopes.values() {
        writeln!(
            source,
            "    ScopeImage::new({}, ReactorIndex::new({}), {}, {}, {}, {}, {}, {}, {}),",
            optional_index("ScopeIndex", value.parent().map(|value| value.as_u32())),
            value.reactor().as_u32(),
            optional_index("ModeIndex", value.mode().map(|value| value.as_u32())),
            table_range(value.descendants()),
            table_range(value.logical_actions()),
            table_range(value.timer_startups()),
            table_range(value.reset_reactions()),
            table_range(value.startup_reactions()),
            table_range(value.shutdown_reactions())
        )?;
    }
    source.push_str("];\n");
    Ok(())
}

fn render_routes(source: &mut String, prefix: &str, image: &EnclaveImage<'_>) -> Result<()> {
    writeln!(
        source,
        "static {prefix}_ROUTES: [RouteImage; {}] = [",
        image.routes.len()
    )?;
    for value in image.routes.values() {
        writeln!(source, "    RouteImage::new({}, PortIndex::new({}), RouteDirection::{}, TimingDomain::{}, {}),", identity_range(value.boundary()), value.local_port().as_u32(), route_direction(value.direction()), timing_domain(value.timing_domain()), value.delay_nanos())?;
    }
    source.push_str("];\n");
    Ok(())
}

fn render_required_bindings(
    source: &mut String,
    prefix: &str,
    image: &EnclaveImage<'_>,
) -> Result<()> {
    writeln!(
        source,
        "static {prefix}_REQUIRED_BINDINGS: [RequiredBindingImage; {}] = [",
        image.required_bindings.len()
    )?;
    for value in image.required_bindings.values() {
        writeln!(
            source,
            "    RequiredBindingImage::new({}, BindingKind::{}),",
            identity_range(value.id()),
            binding_kind(value.kind())
        )?;
    }
    source.push_str("];\n");
    Ok(())
}

fn render_level_reactions(
    source: &mut String,
    name: &str,
    values: &[LevelReactionImage],
) -> Result<()> {
    writeln!(
        source,
        "static {name}: [LevelReactionImage; {}] = [",
        values.len()
    )?;
    for value in values {
        writeln!(
            source,
            "    LevelReactionImage::new({}, ReactionIndex::new({})),",
            value.level(),
            value.reaction().as_u32()
        )?;
    }
    source.push_str("];\n");
    Ok(())
}

fn render_timer_startups(
    source: &mut String,
    name: &str,
    values: &[TimerStartupImage],
) -> Result<()> {
    writeln!(
        source,
        "static {name}: [TimerStartupImage; {}] = [",
        values.len()
    )?;
    for value in values {
        writeln!(
            source,
            "    TimerStartupImage::new(ActionIndex::new({}), {}),",
            value.action().as_u32(),
            value.logical_delay_nanos()
        )?;
    }
    source.push_str("];\n");
    Ok(())
}

fn render_lifecycle_reactions(
    source: &mut String,
    name: &str,
    values: &[LifecycleReactionImage],
) -> Result<()> {
    writeln!(
        source,
        "static {name}: [LifecycleReactionImage; {}] = [",
        values.len()
    )?;
    for value in values {
        writeln!(source, "    LifecycleReactionImage::new(LevelReactionImage::new({}, ReactionIndex::new({})), ActionIndex::new({})),", value.reaction().level(), value.reaction().reaction().as_u32(), value.action().as_u32())?;
    }
    source.push_str("];\n");
    Ok(())
}

fn render_indices(
    source: &mut String,
    name: &str,
    ty: &str,
    values: impl Iterator<Item = u32>,
) -> Result<()> {
    let values = values.collect::<Vec<_>>();
    writeln!(source, "static {name}: [{ty}; {}] = [", values.len())?;
    for value in values {
        writeln!(source, "    {ty}::new({value}),")?;
    }
    source.push_str("];\n");
    Ok(())
}

fn table_range<T>(value: TableRange<T>) -> String {
    format!("TableRange::new({}, {})", value.start(), value.len())
}

fn identity_range(value: IdentityRange) -> String {
    format!("IdentityRange::new({}, {})", value.start(), value.len())
}

fn optional_index(ty: &str, value: Option<u32>) -> String {
    value.map_or_else(
        || String::from("None"),
        |value| format!("Some({ty}::new({value}))"),
    )
}

fn optional_bank(value: Option<BankInfoImage>) -> String {
    value.map_or_else(
        || String::from("None"),
        |value| {
            format!(
                "Some(BankInfoImage::new({}, {}))",
                value.index(),
                value.total()
            )
        },
    )
}

fn action_timing(value: ActionTiming) -> String {
    match value {
        ActionTiming::Standard { domain, min_delay_nanos } => format!("ActionTiming::Standard {{ domain: TimingDomain::{}, min_delay_nanos: {min_delay_nanos} }}", timing_domain(domain)),
        ActionTiming::Timer { period_nanos } => format!("ActionTiming::Timer {{ period_nanos: {period_nanos:?} }}"),
        ActionTiming::Shutdown => String::from("ActionTiming::Shutdown"),
    }
}

fn storage_bounds(value: StorageBounds) -> String {
    format!(
        "StorageBounds::new({}, {}, {}, {}, {}, {})",
        value.state_slots(),
        value.action_slots(),
        value.event_capacity(),
        value.payload_bytes(),
        value.state_bytes(),
        value.scratch_bytes()
    )
}

const fn timing_domain(value: TimingDomain) -> &'static str {
    match value {
        TimingDomain::Logical => "Logical",
        TimingDomain::Physical => "Physical",
    }
}

const fn route_direction(value: RouteDirection) -> &'static str {
    match value {
        RouteDirection::Inbound => "Inbound",
        RouteDirection::Outbound => "Outbound",
    }
}

const fn binding_kind(value: BindingKind) -> &'static str {
    match value {
        BindingKind::StateInitializer => "StateInitializer",
        BindingKind::Reaction => "Reaction",
        BindingKind::Port => "Port",
        BindingKind::Action => "Action",
    }
}

const fn transition(value: TransitionKind) -> &'static str {
    match value {
        TransitionKind::Reset => "Reset",
        TransitionKind::History => "History",
    }
}

#[cfg(test)]
mod tests {
    use boomerang_builder::{ReactionSlot, ReactionSlotId, ReactorSlotId};

    use super::reaction_reactor;

    #[test]
    fn nested_reaction_uses_its_exact_descriptor_owner() {
        let root = ReactorSlotId::new("Root").unwrap();
        let child = ReactorSlotId::new("Root/child").unwrap();
        let reaction = ReactionSlotId::new("Root/child/startup").unwrap();
        let slots = [ReactionSlot {
            id: reaction.clone(),
            reactor: child.clone(),
        }];

        assert_eq!(reaction_reactor(&slots, &reaction).unwrap(), &child);
        assert_ne!(reaction_reactor(&slots, &reaction).unwrap(), &root);
    }
}
