schema = 1

[topology]
package = "snake"
entry = "snake::topology"

[deployments.snake]
bindings.snake = { package = "snake-game", component = "game" }
bindings.keyboard = { package = "snake-keyboard", component = "keyboard" }

federates.host = { groups = [
    "placement/keyboard",
], runtime = "std", recovery = "fail-stop" }

execution = { fast-forward = false, keep-alive = true }
