name: CI

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  commitlint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Commitlint
    steps:
      - name: Run commitlint
        uses: opensource-nepal/commitlint@v1

  clippy:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    name: Clippy
    steps:
      - uses: actions/checkout@v7
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: swatinem/rust-cache@v2
      - name: Check with Clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

  test:
    strategy:
      matrix:
        toolchain: [stable, nightly]
        os: [windows-latest, ubuntu-latest, macos-latest]

        # Only test nightly on Linux
        exclude:
          - os: macos-latest
            toolchain: nightly
          - os: windows-latest
            toolchain: nightly

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v7
      - uses: swatinem/rust-cache@v2
      - name: fetch Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: toolchain version
        run: cargo -vV

      - name: test
        run: cargo test --all --verbose

  miri:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v7
      - uses: swatinem/rust-cache@v2
      - name: fetch Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: miri
      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest
      - name: Test with Miri
        env:
          MIRIFLAGS: -Zmiri-disable-isolation
        run: cargo +nightly miri nextest run
